# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 11:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('total_typos', models.IntegerField(default=0)),
                ('tweet_with_most_typos', models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, to='battles.Tweet')),
            ],
        ),
    ]
